services:

    unitime-db:
        container_name: unitime-db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=timetable
            - MYSQL_PASSWORD=unitime
            - MYSQL_DATABASE=timetable
        expose:
            - 3306
        build:
            context: .
            dockerfile: mysql.Dockerfile
        volumes:
            - "unitime-db:/var/lib/mysql"

    unitime-web:
        depends_on:
            - unitime-db
        container_name: unitime-web
        environment:
            - JAVA_OPTS=-Xmx2g -Dconnection.url=jdbc:mysql://unitime-db:3306/timetable
        build:
            context: .
            dockerfile: tomcat.Dockerfile
        ports:
            - 8888:8080 
        volumes:
            - "unitime-data:/usr/local/tomcat/data"

volumes:
    unitime-data:
    unitime-db: